### ISSUE TITLE
Can't compile freetype.mod

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/pub.mod#16]
```
[ 32%] Compiling:jcparam.c
In file included from /usr/include/freetype2/ft2build.h:37:0,
                 from /BlitzMaxNG/mod/pub.mod/freetype.mod/glue.c:2:
/usr/include/freetype2/freetype/config/ftheader.h:7:65: fatal error: i386-linux-gnu/freetype2/freetype/config/ftheader.h: Datei oder Verzeichnis nicht gefunden
compilation terminated.
```

**Comment by GWRon** [comment]
Ok, did a 
sudo apt-get install libfreetype6-dev:i386
and it compiled.


Now I got
```
[ 53%] Compiling:SDL_gesture.c
BlitzMaxNG/mod/sdl.mod/sdl.mod/SDL/src/audio/esd/SDL_esdaudio.c:31:17: fatal error: esd.h: Datei oder Verzeichnis nicht gefunden
```
So up for the next issue ;-)

**Comment by GWRon** [comment]
sudo apt-get install libesd0-dev
and it installed the necessary header files ... but somehow I think you provide them in the source-directories already.

Afterwards it blamed `SDL_nasaudio.h:29:28` to not find `audio/audiolib.h`
sudo apt-get install libaudio-dev
helped there

**Comment by woollybah** [comment]
On Linux, libfreetype6-dev is required.
