### ISSUE TITLE
Add support for shcore on Win32

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/pub.mod#18]
shcore.dll implements some of the new HiDPI interfaces on Windows 8.1+

We should add this to the set of available APIs in Pub.Win32.

The functions would need to be dynamically loaded so as to be backwards compatible with pre 8.1 Windows.

**Comment by GWRon** [comment]
Shouldn't Linux and Mac get a similar issue/ticket too?

**Comment by woollybah** [comment]
Mac and Linux don't use shcore :-p
