### ISSUE TITLE
lua.mod Compile Error: Expression has no scope

### ISSUE THREAD

**Issue by Jeromelab** [bmx-ng/pub.mod#2]
Compiling:lua.bmx
Compile Error: Expression has no scope
[/Desktop/BlitzMax/mod/pub.mod/lua.mod/lua.bmx;587;0]
gcc: error: /Desktop/BlitzMax/mod/pub.mod/lua.mod/.bmx/lua.bmx.debug.linux.arm.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
Build Error: failed to compile /Desktop/BlitzMax/mod/pub.mod/lua.mod/.bmx/lua.bmx.debug.linux.arm.c

**Comment by Jeromelab** [comment]
freetype, freeprocess and lua not compiling on raspberry pi with the latest raspbian wheezy (5-5-2015)

**Comment by woollybah** [comment]
Everything appears to be working with the latest bcc and bmk. You can download a pre-built set here : https://github.com/bmx-ng/bmx-ng/releases
