### ISSUE TITLE
lua.mod requires Brl.Blitz now ("Min/Max()" no longer inbuilt function)

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/pub.mod#21]
Min and Max( ) are now no inbuilt-functions anymore.

pub.lua is no longer compileable because of this. Adding `Import Brl.Blitz` (which defines these function) does not get rid of the compiler error:

`Compile Error: Identifier 'min' not found.
[/home/ronny/Arbeit/Programmieren/Tools/BlitzMaxNG.Clean/mod/pub.mod/lua.mod/lua.bmx;826;0]`

This is because of the nature how "brl.mod" AND "pub.mod" are compiled ... it tries to compile some pub-stuff without having the brl.mod-stuff being finished:

```
[  0%] Processing:blitz.bmx
[  0%] Processing:appstub.bmx
[  0%] Processing:sample.bmx
[  0%] Processing:font.bmx
[  0%] Processing:hook.bmx
[  0%] Processing:keycodes.bmx
[  0%] Processing:intmap.bmx
[  0%] Processing:objectmap.bmx
[  0%] Processing:ptrmap.bmx
[  0%] Processing:stringmap.bmx
[  1%] Processing:math.bmx
[  1%] Processing:pixel.bmx
[  1%] Processing:random.bmx
[  1%] Processing:driver.bmx
[  1%] Processing:threads.bmx
[  1%] Processing:freetype.bmx
[  1%] Processing:glew00.bmx
[  1%] Processing:glew01.bmx
[  1%] Processing:glew02.bmx
[  1%] Processing:glew03.bmx
[  1%] Processing:glew04.bmx
[  2%] Processing:glew05.bmx
[  2%] Processing:glew06.bmx
[  2%] Processing:glew07.bmx
[  2%] Processing:glew08.bmx
[  2%] Processing:glew09.bmx
[  2%] Processing:glew10.bmx
[  2%] Processing:glew11.bmx
[  2%] Processing:glew12.bmx
[  2%] Processing:glew13.bmx
[  2%] Processing:glew14.bmx
[  3%] Processing:glew15.bmx
[  3%] Processing:libjpeg.bmx
[  3%] Processing:lua.bmx
[  3%] Processing:oggvorbis.bmx
[  3%] Processing:glu.bmx
[  3%] Processing:stdc.bmx
[  3%] Processing:zlib.bmx
[  3%] Processing:linux_source.bmx
[  3%] Processing:common.bmx
[  3%] Processing:common.bmx
[  3%] Processing:common.bmx
Compile Error: Identifier 'min' not found.
[/home/ronny/Arbeit/Programmieren/Tools/BlitzMaxNG.Clean/mod/pub.mod/lua.mod/lua.bmx;826;0]
Build Error: failed to compile (65280) /home/ronny/Arbeit/Programmieren/Tools/BlitzMaxNG.Clean/mod/pub.mod/lua.mod/lua.bmx
Process complete
```

**Comment by HurryStarfish** [comment]
That's odd. BRL.Blitz should definitely be built first. It's supposed to be the one module that's automatically imported in everything else (which is why `Import Brl.Blitz` doesn't do anything) and your output says `Processing:blitz.bmx` at the top as well. I can't right now, but I'll test if I get the same error later.

**Comment by GWRon** [comment]
Yes it compiles the bmx files (bmx->c) but once it reached a certain step it outputs this "archiving..." thing - which creates the .a files (and others) so that an import works.

Until that phase the modules are not finally compiled - you might abort module compilation inbetween and restart it - you will see that these files are again compiled as the "desired result files" were not created yet.

**Comment by woollybah** [comment]
I haven't managed to replicate this - either on Windows or Linux.

**Comment by GWRon** [comment]
- downloaded bcc.git and compiled with previous installation
- put it into "BlitzMaxNG.new/bin"
- downloaded brl.mod/pub.mod/sdl.mod from github and extracted it to "BlitzMaxNG.new/mods" (and renamed folders accordingly)
- put my old maxIDE into "BlitzMaxNG.new"
- started maxIDE and put into the new document:

```BlitzMax
SuperStrict

Framework Brl.StandardIO
Import Pub.Lua

Print "doing something with lua..."
```
- hit compile and receive:
```
Building untitled1
[  0%] Processing:blitz.bmx
[  1%] Processing:appstub.bmx
[  2%] Processing:lua.bmx
[  3%] Processing:stdc.bmx
Compile Error: Identifier 'min' not found.
[/home/ronny/Arbeit/Programmieren/Tools/BlitzMaxNG.new/mod/pub.mod/lua.mod/lua.bmx;824;0]
Build Error: failed to compile (65280) /home/ronny/Arbeit/Programmieren/Tools/BlitzMaxNG.new/mod/pub.mod/lua.mod/lua.bmx
Process complete
```

**Comment by GWRon** [comment]
Added a linux-folder containing: the new modules (version of "added min/max", so abs/sgn are still inubilt), the bcc compiled at the very same revision and a maxide to keep it easy to paste above's sample code.

I know I could first compile the essential brl-modules and from then on it can build pub.mod and then all other brl-modules but ...nah.

[BlitzMaxNG.Clean.zip](https://github.com/bmx-ng/pub.mod/files/2752514/BlitzMaxNG.Clean.zip)

**Comment by woollybah** [comment]
I tried your "clean" BlitzMax. I was unable to replicate the problem in my Linux VM.
It behaves as expected, waiting for blitz.bmx to be processed before processing the next batch of files (which includes lua.bmx).

If you aren't seeing this, then there's something wrong with your configuration somehow.

**Comment by GWRon** [comment]
Amd or linux? Maybe there are subtle differences. 

Am sure it works on m Intel Notebook...

**Comment by woollybah** [comment]
In `bmk_make.bmx`, at around line 715 is :
```blitzmax
?threaded
		processManager.WaitForTasks()
?
```
bmk should wait for the current batch of files to complete before moving onto the next.
The very first "batch" should be brl.blitz - on its own, because everything depends on it.

**Comment by woollybah** [comment]
I should add, that your "clean" zip has a `bcc.conf` file in the bin folder.
Unless you know what you are doing with it, you probably don't want it anywhere near your bin dir.

**Comment by GWRon** [comment]
bla bla bla :pig: ... I do not really like it but ... 

... you were again right. I somehow had this bcc.conf file in it ... leading to ... the usage of my other NG installation (partially). Though it seems to mix up stuff then - on the one hand it does not see the necessarity to compile modules, but on the other hand it does not find the already compiled ones. 

Thanks for having a look at it.
