### ISSUE TITLE
Sound playback with freeaudio+NG or maxmods+vanilla crackling.

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/pub.mod#27]
For my streamed audio I use an integer array to store stereo audio data.

It works without crackled sound in Linux but on my Windows boxes I have some cracks here and there in the audio.

Compiling the same stuff with vanilla leads to "perfect" sound output.

I think there was some adjustments in the way NG handles "arrays" (structure wise). So when passing the integer array via "byte ptr" to eg. ogg_dec (to store decoded ogg data in there) this might create some incompatibilities.

Is there a way to make the same code work on both BlitzMax incarnations or do I need to play with a `TBank` or such a thing?

How would that translate then?

Instead of defining the buffer with `new Int[ bufferlength ]` I tried a `bank.Resize( bufferlength * 2)` (EAV short after start) (and also a `bank.Resize( bufferlength * sizeof(0) )` to fetch the actual size of the integer there - it started with a random noise and then played the music but still crackling).
Instead of passing `byte ptr(integerarray)` I of course used `bank.Lock()`.

Do I have to pay attention to something else?

**Comment by woollybah** [comment]
I'm not sure why one wouldn't just use 2048 everywhere either... and I don't see an issue to make it larger either.

**Comment by GWRon** [comment]
Think I will leave it up to you to update the value (and maybe remove the IsWin98() thing ;-)).

Is there a reason for the DirectSound-FreeAudio-Driver to be disabled?
