### ISSUE TITLE
pub.mod/directx error compiling in debug mode

### ISSUE THREAD

**Issue by xlsior75** [bmx-ng/pub.mod#31]
Cannot recompile pub.mod/directx.mod in debug mode, both x86 and x64.
Latest BCC/BMK, windows.

[ 75%] Compiling:d3d.bmx.debug.win32.x64.c
[ 76%] Compiling:kernel32.bmx.debug.win32.x64.c
[ 76%] Compiling:shell32.bmx.debug.win32.x64.c
[ 76%] Compiling:user32.bmx.debug.win32.x64.c
[ 76%] Compiling:winmm.bmx.debug.win32.x64.c
[ 76%] Compiling:_MM_SHUFFLE.bmx.debug.win32.x64.c
c:/code/BlitzmaxNG810/mod/pub.mod/directx.mod/.bmx/d3d.bmx.debug.win32.x64.c: In function '_pub_directx_d3d_D3DPRESENT_PARAMETERS_Compare_i_vTD3DPRESENT_PARAMETERS':
c:/code/BlitzmaxNG810/mod/pub.mod/directx.mod/.bmx/d3d.bmx.debug.win32.x64.c:1286:4: error: expected expression before '}' token
    },
    ^
c:/code/BlitzmaxNG810/mod/pub.mod/directx.mod/.bmx/d3d.bmx.debug.win32.x64.c: In function '_pub_directx_d3d_D3DSURFACE_DESC_Compare_i_vTD3DSURFACE_DESC':
c:/code/BlitzmaxNG810/mod/pub.mod/directx.mod/.bmx/d3d.bmx.debug.win32.x64.c:1703:4: error: expected expression before '}' token
    },
    ^
[ 76%] Compiling:sse.bmx.debug.win32.x64.c
Build Error: failed to compile (1) c:/code/BlitzmaxNG810/mod/pub.mod/directx.mod/.bmx/d3d.bmx.debug.win32.x64.c

**Comment by xlsior75** [comment]
Any idea?

**Comment by woollybah** [comment]
Should be working now with the latest bcc.
