### ISSUE TITLE
[Suggestion] Add shutdown() into closesocket_()

### ISSUE THREAD

**Issue by AXKuhta** [bmx-ng/pub.mod#44]
```diff
diff --git a/stdc.c b/stdc.c
index 57c0424..d0d1163 100644
--- a/stdc.c
+++ b/stdc.c
@@ -543,6 +543,8 @@ int socket_( int addr_type,int comm_type,int protocol ){
 }
 
 void closesocket_( int s ){
+	shutdown( s, 2 );
+
 #if _WIN32
 	closesocket( s );
 #else
```

This fixes a very specific hang condition in my [small web server](https://github.com/AXKuhta/ObscureServer/). In situations where there's no Content-Length header available, cURL based clients would hang waiting for data indefinitely, even after CloseSocket() was called on the server. Debugging in WireShark showed that the TCP connection was in fact not closed, TCP keepalive pings still flying both directions. 

^C-ing the server caused cURL to exit its loop somehow. Further investigation revealed that this is because a FIN packet is emitted on the connection when the server closes.

Adding shutdown() here allows to emit a FIN packet in an orderly fashion when the socket is closed.

This fixed the cURL problem and seems to work fine on x64 Windows and Linux.

**Comment by GWRon** [comment]
Maybe provide a flag one can set...so it is jot automatically shutdown... Just thinking about the "edge case"

**Comment by AXKuhta** [comment]
Yes, a flag that is enabled by default would be preferable, but I suppose this works too. Thank you.
